### ISSUE TITLE
NSString comparsion operators -- CONTAINS/LIKE -- it doesn't work on NSData.

### ISSUE THREAD

**Issue by hisavali** [DavidBenko/Encrypted-Core-Data#3]
Hi @DavidBenko,

Thanks for creating this piece of example for field level encryption.

Problem: 
Once encrypted values are stored as NSData in persistent store, if fetch takes place with NSPredicate which uses string (not basic) comparisons operators -- CONTAINS/LIKE -- it doesn't work for NSData.

Note: I have to stop having random values for 'iv' & 'salt' generated in DataGenerator.m
Please find my code changes in gist listed below. I have provided comments against working & non-working code.

Question: In order to fetch data, how to form sql query (predicate) with string operators 'like, contains or match' for encrypted data.

Please find more information here:
https://gist.github.com/hisavali/b15a4a8e875c73458d80

Your insight & help will be appreciated.

**Comment by DavidBenko** [comment]
@hisavali okay, you might not like this answer - from the small amount of research I did (haven't personally tested yet), it looks like sorting and predicates are done on the values in the database, not the decrypted ones - which makes sense. Apple isn't going to want to load up and transform everything in what could be a very large database in order to search for one thing. 

So I have a few possible solutions for you. 

1) Turn on 'Data Protection' and don't use further software encryption. This is the easiest route and is provided by Apple. If an encryption key is stored on a jailbroken device (even in the keychain) it can still be retrieved (from memory even, using cycript if you wanted) which makes encryption on iOS iffy at best. If this satisfies your security requirements, this is the route I would go. 

If you need further data-at-rest encryption on the core data store, continue reading.

2) Use an in-memory store. You could decrypt the values in the coredata store and keep them decrypted in-memory store. This would work if you have a lot of queries and/ or a LOT of records, but is a lot of overhead. You might need to worry about someone terminating the app with the database open, as this could be insecure.

3) Grab all the records you would need and query on that. Pull all of the records you *could* need for what you are working on and keep them in-memory in an NSArray or NSSet or something. This won't work for large sets of data though.

**Comment by hisavali** [comment]
Thanks for your insight @DavidBenko 

Our team is already using point (3) along with NSFetchedResultsController. And trust me, it gives lots of pain of mapping indices (insert, update, delete, move) between FRC & in-memory NS-Data structures.
It is always pro-maintenance.


In my opinion, Apple should have taken NSValueTransformer a step further to let implementer decides how she wants to process the components of predicate query.

Well, Thanks again and nice chatting with you.

**Comment by DavidBenko** [comment]
:+1:
